### ISSUE TITLE
Mopub imports fails

### ISSUE THREAD

**Issue by pablogeek** [Mintegral-official/mintegral_mopub_adapter_ios#1]
The app won't compile because it cannot find MoPub.h it is fixed with `#import <MoPub/MoPub.h>`

![Screenshot 2020-05-28 at 10 38 12](https://user-images.githubusercontent.com/1773546/83118945-569c9c00-a0cf-11ea-93df-f9df8382df17.png)

**Comment by zhangchark** [comment]
thank you for your information, the issue had been fixed.
